AddBountyPerKill: 2000
PayForMobKills: false
MobKillMessages: true
BountyLevel:
  rebel: 1000
  pettycriminal: 2500
  bandit: 5000
  rogue: 10000
  ruffian: 25000
  thug: 50000
  outlaw: 100000
  hitman: 175000
  mafiaboss: 300000
MobMoney:
  Chicken: 0
  Pig: 0
  Cow: 0
  Sheep: 0
  Creeper: 20
  Skeleton: 10
  Zombie: 10
  Enderman: 10
  Spider: 10
  Bat: 0
  Blaze: 20
  CaveSpider: 10
  ChestedHorse: 0
  Donkey: 0
  ElderGuardian: 1000
  EnderDragon: 1000
  Endermite: 10
  Ghast: 50
  Giant: 250
  Guardian: 100
  Horse: 0
  IronGolem: 0
  Llama: 0
  MagmaCube: 10
  Mule: 0
  MushroomCow: 0
  Ocelot: 0
  PigZombie: 10
  PolarBear: 0
  Rabbit: 0
  Silverfish: 10
  SkeletonHorse: 0
  Slime: 10
  Snowman: 0
  Squid: 0
  Witch: 30
  Wither: 1000
  WitherSkeleton: 30
  Wolf: 0
  ZombieHorse: 0
  ZombieVillager: 0
Bounty:
  zargon_king: 1099998
  nightghost2: 0
  spyjay_yt: 6000
  melonketchum: 0
  umbyy: 0
  spid0207: 0
  hotchilliz: 0
  bloodcorn: 0
  maydayparker: 0
  demonisef: 4000
  regner_21: 0
  moosei: 0
  sykaos: 0
  andreimcu: 0
  solvinq: 0
  _wonderbat_: 0
  thatcraftlife: 4000
  agent__cj: 0
  moomoothepirate: 0
LastKilled:
  spyjay_yt:
    nightghost2: 04/10/17
    zargon_king: 04/10/17
    umbyy: 04/10/17
  umbyy:
    zargon_king: 04/10/17
