# 
# Whether or not resourcepack file hashes should be generated on startup:
debug: true
autogeneratehashes: true
messages:
  usepack: You now use the pack %pack%!
  packlisthead: 'Packs available to you:'
  nopacks: No packs found!
packs:
  lobbypack:
    url: http://example.com/lobbyresourcepack.zip
    hash: abcdef012345678abcdef012345678abcdef0123
    format: 1
    restricted: false
    permission: worldresourcepacks.pack.lobbypack
  gamepack:
    url: http://example.com/minigameresourcepack.zip
    hash: 012345678abcdef012345678abcdef012345678a
    format: 0
    restricted: false
    permission: worldresourcepacks.pack.gamepack
  emptypack:
    url: http://cdn.moep.tv/files/Empty.zip
    hash: e5d91e14e9c685b06f00e550d9e189deb2075f76
    format: 0
    restricted: false
    permission: worldresourcepacks.pack.emptypack
empty: emptypack
server:
  pack: lobbypack
worlds:
  lobby:
    pack: lobbypack
  minigame:
    pack: gamepack
